# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AppRoleAssignment(Model):
    """AppRoleAssignment.

    :param id:
    :type id: str
    :param creation_timestamp:
    :type creation_timestamp: datetime
    :param principal_display_name:
    :type principal_display_name: str
    :param principal_id:
    :type principal_id: str
    :param principal_type:
    :type principal_type: str
    :param resource_display_name:
    :type resource_display_name: str
    :param resource_id:
    :type resource_id: str
    :param app_role_id:
    :type app_role_id: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'creation_timestamp': {'key': 'creationTimestamp', 'type': 'iso-8601'},
        'principal_display_name': {'key': 'principalDisplayName', 'type': 'str'},
        'principal_id': {'key': 'principalId', 'type': 'str'},
        'principal_type': {'key': 'principalType', 'type': 'str'},
        'resource_display_name': {'key': 'resourceDisplayName', 'type': 'str'},
        'resource_id': {'key': 'resourceId', 'type': 'str'},
        'app_role_id': {'key': 'appRoleId', 'type': 'str'},
    }

    def __init__(self, *, id: str=None, creation_timestamp=None, principal_display_name: str=None, principal_id: str=None, principal_type: str=None, resource_display_name: str=None, resource_id: str=None, app_role_id: str=None, **kwargs) -> None:
        super(AppRoleAssignment, self).__init__(**kwargs)
        self.id = id
        self.creation_timestamp = creation_timestamp
        self.principal_display_name = principal_display_name
        self.principal_id = principal_id
        self.principal_type = principal_type
        self.resource_display_name = resource_display_name
        self.resource_id = resource_id
        self.app_role_id = app_role_id
