resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools

trigger: none

pr: none

stages:
- template: ../../eng/pipelines/templates/jobs/archetype-sdk-client.yml
